source_list:
  - CP

target_list:
  - CHILD_DIM

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data
      filename: receipts_delta_GBR_14_10_2017.csv

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

CP:
  s3_conf:
    s3_bucket: practicebuckettarun
    filename: KC_Extract_1_20171009.csv

ADDR:
  mongodb_config:
    database: cust
    collection: address

REGIS_DIM:
  tableName: DATAMART.REGIS_DIM
  source_data: CP
  loadingQuery: >
    SELECT
      MONOTONICALLY_INCREASING_ID() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
      REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
    FROM
      (SELECT
        DISTINCT REGIS_CNSM_ID, CAST(REGIS_CTY_CODE AS SMALLINT), CAST(REGIS_ID AS INTEGER),
        REGIS_LTY_ID, REGIS_DATE, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
      FROM
        CP
      WHERE
        INS_DT = CURRENT_DATE
      ) CP

CHILD_DIM:
  tableName: DATAMART.CHILD_DIM
  source_data: CP
  loadingQuery: >
      SELECT
          MONOTONICALLY_INCREASING_ID() CHILD_KEY, REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB,
          CHILD_GENDER, INS_DT
      FROM
           (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, INS_DT
      FROM
          CP
      WHERE
          INS_DT = '2021-06-26' AND CHILD_ID IS NOT NULL
      ) CP


s3_conf:
  s3_bucket: practicebuckettarun
  staging_dir: staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT



